package deckOfCards;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;

/* This class helps instantiate a standard deck of 52 cards containing an arrayList of cards
 */
public class Deck {

	private ArrayList<Card> cards;
	
	/* Standard Constructor which takes in no parameters and instantiates the list of 52 cards representing a deck */
	public Deck() {
		cards = new ArrayList<>();
		for (Suit suit : Suit.values()) {
			for (Rank rank : Rank.values()) {
				cards.add(new Card(rank, suit));
			}
		}
	}
	
	/* This instance method takes in one parameter generated by the random module and shuffles the list of cards using
	 * the shuffle method of the Collections class. 
	 */
	public void shuffle(Random randomNumberGenerator) {
		Collections.shuffle(cards, randomNumberGenerator);
	}
	
	/* This method returns the Card at the first index of the list of cards and removes it at the same time */
	public Card dealOneCard() {
		Card returnValue = cards.get(0);
		cards.remove(0);
		return returnValue;
	}
}
